<?php

declare(strict_types=1);

return [
    'name' => 'Pedidos',
    'entity' => 'Pedido',
    'slug' => 'pedidos',
    'icon' => '🛍️',
    'description' => 'Registro e acompanhamento de vendas e pedidos realizados.',
    'prefix' => 'ped',
    'storage' => 'pedidos.csv',
    'permission_prefix' => 'pedidos',
    'fields' => [
        'numero' => [
            'label' => 'Código do Pedido',
            'type' => 'string',
            'required' => true,
            'unique' => true,
            'list' => true,
            'help' => 'Identificador comercial (ex: PED-1001).',
        ],
        'cliente_id' => [
            'label' => 'Cliente',
            'type' => 'relation',
            'target' => 'clientes',
            'display' => 'nome',
            'on_delete' => 'restrict',
            'required' => true,
            'unique' => false,
            'list' => true,
            'help' => 'Cliente que efetuou a compra.',
        ],
        'produto_id' => [
            'label' => 'Produto Adquirido',
            'type' => 'relation',
            'target' => 'produtos',
            'display' => 'nome',
            'on_delete' => 'restrict',
            'required' => true,
            'unique' => false,
            'list' => true,
            'help' => 'Produto principal solicitado.',
        ],
        'quantidade' => [
            'label' => 'Quantidade',
            'type' => 'number',
            'required' => true,
            'unique' => false,
            'list' => true,
            'help' => 'Número de unidades compradas.',
        ],
        'valor_total' => [
            'label' => 'Valor Total (R$)',
            'type' => 'number',
            'required' => true,
            'unique' => false,
            'list' => true,
            'help' => 'Valor final cobrado no pedido.',
        ],
        'status' => [
            'label' => 'Status do Pedido',
            'type' => 'select',
            'options' => [
                'Pendente',
                'Aprovado',
                'Em Transporte',
                'Entregue',
                'Cancelado',
            ],
            'required' => true,
            'unique' => false,
            'list' => true,
        ],
        'data_pedido' => [
            'label' => 'Data da Compra',
            'type' => 'date',
            'required' => true,
            'unique' => false,
            'list' => true,
        ],
        'observacoes' => [
            'label' => 'Observações / Endereço de Entrega',
            'type' => 'text',
            'required' => false,
            'unique' => false,
            'list' => false,
            'help' => 'Instruções de despacho e notas fiscais.',
        ],
    ],
];
